"""Paystack billing — per-child metered invoices (GuardianPD spec).

Code-complete but requires your own Paystack account: set
PAYSTACK_SECRET_KEY in .env. Until it's set, checkout-session creation
returns a clear 501 rather than a fake URL — unlike email/push, there's no
meaningful stand-in for "here's where to pay."

Unlike the old flat-plan approach, there is no Paystack "Plan" here at all:
each Invoice has its own amount (child_count * 500 NGN, generated by
app/jobs/generate_invoices.py), so every checkout is a one-off
transaction (/transaction/initialize) for that invoice's exact amount
rather than a subscription to a fixed-price Plan. Paystack amounts are in
the smallest currency unit (kobo for NGN), hence the *100 conversion below.

Webhooks are verified with the *same* secret key (HMAC-SHA512 of the raw
body, compared against the `x-paystack-signature` header) rather than a
separate signing secret — so there's no PAYSTACK_WEBHOOK_SECRET setting.
Paying an invoice does NOT automatically reactivate a suspended school —
see Subscription's docstring in app/models/platform.py — that's a
deliberate Master Admin action via the deactivate/reactivate endpoints
below (the Manage Subscription page).
"""

import datetime as dt
import hashlib
import hmac
import uuid

import httpx
from fastapi import APIRouter, Depends, HTTPException, Request
from sqlalchemy.orm import Session

from app.api.deps import require_platform_staff
from app.core.config import settings
from app.db.platform import get_platform_db
from app.models.platform import Invoice, School, Subscription
from app.schemas.billing import CheckoutSessionResponse, InvoiceOut

router = APIRouter(prefix="/platform", tags=["billing"])

PAYSTACK_API_BASE = "https://api.paystack.co"


def _invoice_out(invoice: Invoice, school_name: str) -> dict:
    return {
        "id": invoice.id,
        "school_id": invoice.school_id,
        "school_name": school_name,
        "period_start": invoice.period_start,
        "period_end": invoice.period_end,
        "child_count": invoice.child_count,
        "amount_naira": invoice.amount_naira,
        "status": invoice.status,
        "due_date": invoice.due_date,
        "paid_at": invoice.paid_at,
        "created_at": invoice.created_at,
    }


@router.get(
    "/invoices",
    response_model=list[InvoiceOut],
    dependencies=[Depends(require_platform_staff)],
)
def list_invoices(status: str = "unpaid", platform_db: Session = Depends(get_platform_db)) -> list[dict]:
    """`status` is one of:
    - "upcoming": pending invoices not yet due (Billing page)
    - "unpaid": pending or overdue invoices already past their due date (Manage Subscription page)
    - "overdue": invoices the generate_invoices job has flagged overdue specifically
    - "all": every invoice, most recent first
    """
    today = dt.date.today()
    q = platform_db.query(Invoice)
    if status == "upcoming":
        q = q.filter(Invoice.status == "pending", Invoice.due_date >= today)
    elif status == "unpaid":
        q = q.filter(Invoice.status.in_(("pending", "overdue")), Invoice.due_date < today)
    elif status == "overdue":
        q = q.filter(Invoice.status == "overdue")
    elif status != "all":
        raise HTTPException(status_code=400, detail="status must be one of: upcoming, unpaid, overdue, all")

    invoices = q.order_by(Invoice.due_date.asc()).all()
    schools_by_id = {school.id: school.name for school in platform_db.query(School).all()}
    return [_invoice_out(invoice, schools_by_id.get(invoice.school_id, "Unknown school")) for invoice in invoices]


@router.post(
    "/schools/{school_id}/deactivate",
    dependencies=[Depends(require_platform_staff)],
)
def deactivate_school(school_id: uuid.UUID, platform_db: Session = Depends(get_platform_db)) -> dict:
    """Manage Subscription page: suspends QR scanning/issuance for this
    school (enforced by require_active_subscription, app/api/deps.py).
    """
    subscription = platform_db.query(Subscription).filter_by(school_id=school_id).first()
    if subscription is None:
        raise HTTPException(status_code=404, detail="No subscription found for this school")
    subscription.status = "suspended"
    platform_db.commit()
    return {"status": "updated", "subscription_status": subscription.status}


@router.post(
    "/schools/{school_id}/reactivate",
    dependencies=[Depends(require_platform_staff)],
)
def reactivate_school(school_id: uuid.UUID, platform_db: Session = Depends(get_platform_db)) -> dict:
    subscription = platform_db.query(Subscription).filter_by(school_id=school_id).first()
    if subscription is None:
        raise HTTPException(status_code=404, detail="No subscription found for this school")
    subscription.status = "active"
    platform_db.commit()
    return {"status": "updated", "subscription_status": subscription.status}


@router.post(
    "/invoices/{invoice_id}/checkout-session",
    response_model=CheckoutSessionResponse,
    dependencies=[Depends(require_platform_staff)],
)
def create_checkout_session(invoice_id: uuid.UUID, platform_db: Session = Depends(get_platform_db)) -> dict:
    if not settings.paystack_secret_key:
        raise HTTPException(status_code=501, detail="Paystack is not configured (PAYSTACK_SECRET_KEY unset)")

    invoice = platform_db.get(Invoice, invoice_id)
    if invoice is None:
        raise HTTPException(status_code=404, detail="Unknown invoice")

    school = platform_db.get(School, invoice.school_id)
    if school is None or not school.billing_email:
        raise HTTPException(status_code=409, detail="This school has no billing email on file")

    response = httpx.post(
        f"{PAYSTACK_API_BASE}/transaction/initialize",
        headers={"Authorization": f"Bearer {settings.paystack_secret_key}"},
        json={
            "email": school.billing_email,
            "amount": invoice.amount_naira * 100,  # kobo
            "callback_url": settings.paystack_callback_url,
            # Echoed back on the webhook event — how we correlate the
            # payment back to a specific invoice.
            "metadata": {"invoice_id": str(invoice.id)},
        },
        timeout=10,
    )
    body = response.json()
    if not body.get("status"):
        raise HTTPException(status_code=502, detail=f"Paystack error: {body.get('message', 'unknown error')}")

    return {"checkout_url": body["data"]["authorization_url"]}


@router.post("/billing/webhook")
async def paystack_webhook(request: Request, platform_db: Session = Depends(get_platform_db)) -> dict:
    """Not gated by require_platform_staff — Paystack calls this directly,
    and authenticity is verified via the webhook signature instead.
    """
    if not settings.paystack_secret_key:
        raise HTTPException(status_code=501, detail="Paystack secret key not configured")

    payload = await request.body()
    signature = request.headers.get("x-paystack-signature", "")
    expected_signature = hmac.new(settings.paystack_secret_key.encode(), payload, hashlib.sha512).hexdigest()
    if not hmac.compare_digest(signature, expected_signature):
        raise HTTPException(status_code=400, detail="Invalid Paystack webhook signature")

    event = await request.json()
    if event.get("event") == "charge.success":
        data = event.get("data") or {}
        invoice_id = (data.get("metadata") or {}).get("invoice_id")
        if invoice_id:
            invoice = platform_db.get(Invoice, uuid.UUID(invoice_id))
            if invoice is not None and invoice.status != "paid":
                invoice.status = "paid"
                invoice.paid_at = dt.datetime.now(dt.timezone.utc)
                invoice.paystack_reference = data.get("reference")
                platform_db.commit()

    return {"status": "ok"}
