"""Platform (central) DB models — ARCHITECTURE.md §3."""

import uuid
from datetime import date, datetime
from datetime import time as dt_time

from sqlalchemy import Boolean, Date, DateTime, ForeignKey, Identity, Integer, String, Time, UniqueConstraint, func
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db.platform import PlatformBase


class School(PlatformBase):
    __tablename__ = "schools"

    id: Mapped[uuid.UUID] = mapped_column(PGUUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    # Postgres-generated (IDENTITY), not app-computed — auto-generated and
    # race-free by construction. Displayed/searched as "GPD-{sequence_no:06d}";
    # that formatting is done client-side, not stored redundantly here.
    sequence_no: Mapped[int] = mapped_column(Integer, Identity(always=False), unique=True)
    name: Mapped[str] = mapped_column(String(255))
    slug: Mapped[str] = mapped_column(String(100), unique=True)
    tenant_db_name: Mapped[str] = mapped_column(String(63), unique=True)
    status: Mapped[str] = mapped_column(String(20), default="trial")
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    address: Mapped[str | None] = mapped_column(String(500), nullable=True)
    phone: Mapped[str | None] = mapped_column(String(30), nullable=True)

    # Archiving (not a hard delete — see app/api/routes/schools.py) removes
    # the school from the default dashboard list and blocks staff
    # login/scanning (app/api/deps.py's get_school), but the tenant database
    # and every record in it stay physically intact and recoverable via
    # POST /platform/schools/{id}/unarchive.
    archived_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    # Welfare-email job config (ARCHITECTURE.md §7). Cutoff times are local
    # wall-clock times in this school's own timezone (IANA identifier, e.g.
    # "America/New_York") — app/jobs/welfare_check.py converts UTC "now"
    # into each school's local time before comparing, so schools in
    # different timezones are handled correctly.
    welfare_email_enabled: Mapped[bool] = mapped_column(Boolean, default=True)
    drop_off_cutoff_time: Mapped[dt_time] = mapped_column(Time, default=dt_time(9, 30))
    pickup_cutoff_time: Mapped[dt_time] = mapped_column(Time, default=dt_time(18, 0))
    timezone: Mapped[str] = mapped_column(String(64), default="UTC")

    # Paystack needs a customer email to initialize a checkout transaction
    # (ARCHITECTURE.md §4) — defaults to the school admin's email at
    # enrollment, since School has no other stored contact.
    billing_email: Mapped[str | None] = mapped_column(String(255), nullable=True)


class Subscription(PlatformBase):
    """Manual active/trial/suspended state, controlled from the Master
    Admin's Manage Subscription page (ARCHITECTURE.md §4) — reactivation is
    a deliberate admin action, not something a Paystack webhook flips
    automatically, so paying an invoice does not by itself unsuspend a
    school (see app/api/routes/billing.py).
    """

    __tablename__ = "subscriptions"

    id: Mapped[uuid.UUID] = mapped_column(PGUUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    school_id: Mapped[uuid.UUID] = mapped_column(PGUUID(as_uuid=True), ForeignKey("schools.id"), unique=True)
    # active / trial / suspended — see ARCHITECTURE.md §4 for what each
    # gates. Trial keeps full scanning/issuance access (app/api/deps.py's
    # require_active_subscription) but is never auto-invoiced
    # (app/jobs/generate_invoices.py only bills status == "active").
    status: Mapped[str] = mapped_column(String(20), default="active")
    # Billing anchor date: invoice periods are started_at + N*30 days.
    started_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    # Per-school override of the flat 500 NGN/child rate (Master Admin can
    # adjust this up/down in 500 NGN increments) — read by
    # app/jobs/generate_invoices.py and the manual-invoice endpoint instead
    # of a hardcoded constant.
    price_per_child_naira: Mapped[int] = mapped_column(Integer, default=500)


class Invoice(PlatformBase):
    """One 30-day metered-billing cycle for one school — 500 NGN per
    enrolled child (ARCHITECTURE.md §4), generated by
    app/jobs/generate_invoices.py. Unique on (school_id, period_start) so
    the job is safe to run more than once without double-billing.
    """

    __tablename__ = "invoices"
    __table_args__ = (UniqueConstraint("school_id", "period_start", name="uq_invoice_school_period"),)

    id: Mapped[uuid.UUID] = mapped_column(PGUUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    school_id: Mapped[uuid.UUID] = mapped_column(PGUUID(as_uuid=True), ForeignKey("schools.id"))
    period_start: Mapped[date] = mapped_column(Date)
    period_end: Mapped[date] = mapped_column(Date)
    child_count: Mapped[int] = mapped_column(Integer)
    amount_naira: Mapped[int] = mapped_column(Integer)
    # pending / paid / overdue / cancelled
    status: Mapped[str] = mapped_column(String(20), default="pending")
    due_date: Mapped[date] = mapped_column(Date)
    paystack_reference: Mapped[str | None] = mapped_column(String(255), nullable=True)
    paid_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())


class PlatformUser(PlatformBase):
    """A parent's single login identity, shared across every enrolled school they touch."""

    __tablename__ = "platform_users"

    id: Mapped[uuid.UUID] = mapped_column(PGUUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    name: Mapped[str] = mapped_column(String(255))
    email: Mapped[str] = mapped_column(String(255), unique=True)
    phone: Mapped[str | None] = mapped_column(String(30), nullable=True)
    password_hash: Mapped[str | None] = mapped_column(String(255), nullable=True)
    email_verified: Mapped[bool] = mapped_column(default=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    # Set when a guardian record is first created (ARCHITECTURE.md §8) and
    # cleared once the parent activates their account via /auth/parent/activate.
    invite_token: Mapped[str | None] = mapped_column(String(64), nullable=True)
    invite_token_expires_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)


class GuardianMembership(PlatformBase):
    """Maps a parent's platform login to their Guardian row inside one school's tenant DB."""

    __tablename__ = "guardian_memberships"

    id: Mapped[uuid.UUID] = mapped_column(PGUUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    platform_user_id: Mapped[uuid.UUID] = mapped_column(PGUUID(as_uuid=True), ForeignKey("platform_users.id"))
    school_id: Mapped[uuid.UUID] = mapped_column(PGUUID(as_uuid=True), ForeignKey("schools.id"))
    # No FK — this UUID lives in a different physical database (the school's tenant DB).
    tenant_guardian_id: Mapped[uuid.UUID] = mapped_column(PGUUID(as_uuid=True))


class PlatformStaffUser(PlatformBase):
    """Your own ops team (school enrollment, billing support) — distinct from a school's own staff."""

    __tablename__ = "platform_staff_users"

    id: Mapped[uuid.UUID] = mapped_column(PGUUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    name: Mapped[str] = mapped_column(String(255))
    email: Mapped[str] = mapped_column(String(255), unique=True)
    password_hash: Mapped[str] = mapped_column(String(255))
    role: Mapped[str] = mapped_column(String(50), default="ops")
