"""add qr print tracking and audit log

Revision ID: c309bd135068
Revises: 
Create Date: 2026-09-05 13:29:50.859021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c309bd135068'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('actor_label', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # server_default backfills any already-issued QR credentials to 0
    # prints — the model's Python-side default=0 only applies to new rows.
    op.add_column(
        'qr_credentials', sa.Column('print_count', sa.Integer(), nullable=False, server_default='0')
    )
    op.add_column('qr_credentials', sa.Column('last_printed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qr_credentials', 'last_printed_at')
    op.drop_column('qr_credentials', 'print_count')
    op.drop_table('audit_log_entries')
    # ### end Alembic commands ###
