"""add invite token attempts to platform_users

Revision ID: 429b4639300a
Revises: f22337b7720f
Create Date: 2026-09-06 09:12:48.710393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '429b4639300a'
down_revision: Union[str, None] = 'f22337b7720f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows (there are already-enrolled
    # guardians) to 0 attempts — the model's Python-side default=0 only
    # applies to brand-new INSERTs, not existing ones.
    op.add_column(
        'platform_users',
        sa.Column('invite_token_attempts', sa.Integer(), nullable=False, server_default='0'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platform_users', 'invite_token_attempts')
    # ### end Alembic commands ###
