"""add price_per_child_naira to subscriptions

Revision ID: f22337b7720f
Revises: 
Create Date: 2026-09-05 13:29:09.161976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f22337b7720f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows (there are already-enrolled
    # schools) to the same 500 NGN the model's Python-side default=500
    # would only apply to brand-new INSERTs, not existing ones.
    op.add_column(
        'subscriptions',
        sa.Column('price_per_child_naira', sa.Integer(), nullable=False, server_default='500'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'price_per_child_naira')
    # ### end Alembic commands ###
